version: '3'
services:
  simple-user:
    image: 271733717185.dkr.ecr.us-east-2.amazonaws.com/simple-user:1.2
    ports:
      - "8086:8086"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - "mongodb"
#    restart: always   -> if we don't depend on mongo
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
